<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenGL.Net" Version="0.8.4" />
    <PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

</Project>
